### PR TITLE
initdata: enhance the initdata spec for PeerPod and IBM SE

### PR DESCRIPTION
**Pull request by huoqifeng**
Added IBM SE fields for initdata
Added examples for digest calculation in PeerPod

Depends on: 
- [X] https://github.com/confidential-containers/cloud-api-adaptor/pull/1912/

### CODE REVIEW

**Comment by huoqifeng** [comment]
CC @Xynnn007 @fitzthum @ChengyuZhu6 @mkulke @jialez0

**Review by Xynnn007 — COMMENTED** [review]
Hi @huoqifeng , as initdata might not only face to CoCo. I suggest have detailed information, such as the content of the toml of this PR be in another doc like in peerpod. In this document, only leave a link to that doc. Just like https://github.com/confidential-containers/trustee/blob/main/kbs/docs/initdata.md#confidential-containers does. wdyt?

**Comment by huoqifeng** [comment]
> Hi @huoqifeng , as initdata might not only face to CoCo. I suggest have detailed information, such as the content of the toml of this PR be in another doc like in peerpod. In this document, only leave a link to that doc. Just like https://github.com/confidential-containers/trustee/blob/main/kbs/docs/initdata.md#confidential-containers does. wdyt?

OK, I'll move these contents to https://github.com/confidential-containers/cloud-api-adaptor and make a link in this PR. Thanks! @Xynnn007

**Comment by huoqifeng** [comment]
Waiting the linked page to be available in https://github.com/confidential-containers/cloud-api-adaptor

**Review by ChengyuZhu6 — APPROVED** [review]
LGTM

**Comment by huoqifeng** [comment]
@Xynnn007 the PR in PeerPod has been merged and the link updated in this PR, may you please check it?

**Review by Xynnn007 — APPROVED** [review]
LGTM

**Review by mkulke — APPROVED** [review]

**Pull request merged**
