### PR TITLE
Derive Debug for Data and Enums

### PR DESCRIPTION
**Pull request by ssolit**
Hey, it would be nice to be able to debug these types and make serialization easier. I hope you would consider merging this.

### CODE REVIEW

**Comment by Xynnn007** [comment]
Hi @ssolit  The error here is likely to be accidental, and subsequent retries are based on the first cache, so the error continues. I tested it locally with no errors. Can you help force push this PR and use different commit information to trigger CI execution?

**Comment by ssolit** [comment]
I believe I did what you requested. I rebased off of the latest dependabot commit in origin/main and mildly changed the commit message.

I can't see if this is going to work on my end because the workflows are skipped until there's an approving review. If it doesn't work again should I create a fresh PR?

**Comment by ssolit** [comment]
It seems now "CoCo-AS Rust Suites / Check (pull_request)" is failing. However it succeeds when I run it locally

**Comment by fitzthum** [comment]
Re-running. Let's see if the caching works out.

@Xynnn007 maybe we should take another look at how we are [comparing the errors](https://github.com/confidential-containers/trustee/blob/main/deps/verifier/src/tdx/claims.rs#L559-L560) in the test. That may be a bit error-prone.

I had some trouble comparing errors in some other tests and introduced a weird [compare errors](https://github.com/ssolit/trustee/blob/main/kbs/src/policy_engine/opa/mod.rs#L79-L95) function. I'm not sure if there is a great generic way to do it.

**Comment by Xynnn007** [comment]
Hi @ssolit , the error is not related to your PR I believe. I have put a PR for the CI error https://github.com/confidential-containers/trustee/pull/538

Let's take a rebase after that gets merged and hopefully all will be green

**Comment by Xynnn007** [comment]
@ssolit hey, could you help to take a rebase of this PR? #538 fixed the CI error I think hopefully

**Comment by fitzthum** [comment]
Thanks @ssolit

**Comment by ssolit** [comment]
Thank you all for help getting the change in

**Pull request merged**
