### PR TITLE
bump: guest-components to candidate v0.9.0

### PR DESCRIPTION
**Pull request by Xynnn007**
This is for cutting release of v0.9.0 of trustee. To align with guest-components side.

### CODE REVIEW

**Review by fitzthum — APPROVED** [review]
LGTM

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Xynnn007!

**Comment by Xynnn007** [comment]
Let me change the rev after https://github.com/confidential-containers/guest-components/pull/596 gets merged.

**Review by fitzthum — APPROVED** [review]
LGTM

**Pull request merged**
