### PR TITLE
prep for: let AS to initiate nonce/challenge

### PR DESCRIPTION
**Pull request by mythi**
ref: #162 / 1.

### CODE REVIEW

**Comment by Xynnn007** [comment]
There are some overlap and coherance of [this PR](https://github.com/confidential-containers/trustee/pull/345/files). Let me do some refactoring upon the nonce generation logic after #345 gets merged.

**Comment by mythi** [comment]
> Let me do some refactoring upon the nonce generation logic after #345 gets merged.

I can also move this out of draft and get it merged if it helps.

**Comment by mythi** [comment]
> > Let me do some refactoring upon the nonce generation logic after #345 gets merged.
> 
> I can also move this out of draft and get it merged if it helps.

It also looks that fdbaa417f758ab5541ccda595b007e8d4887f0bf could be moved to a separate PR and have #345 rebased to use that.

**Comment by mythi** [comment]
> > > Let me do some refactoring upon the nonce generation logic after #345 gets merged.
> > 
> > 
> > I can also move this out of draft and get it merged if it helps.
> 
> It also looks that [fdbaa41](https://github.com/confidential-containers/trustee/commit/fdbaa417f758ab5541ccda595b007e8d4887f0bf) could be moved to a separate PR and have #345 rebased to use that.

I made this PR to include the necessary prep work only.

**Comment by mythi** [comment]
> > > Let me do some refactoring upon the nonce generation logic after #345 gets merged.
> > 
> > 
> > I can also move this out of draft and get it merged if it helps.
> 
> It also looks that [fdbaa41](https://github.com/confidential-containers/trustee/commit/fdbaa417f758ab5541ccda595b007e8d4887f0bf) could be moved to a separate PR and have #345 rebased to use that.

too late for now so closing

**Pull request closed without merging**
