### PR TITLE
ita: add USER_AGENT to HTTP header

### PR DESCRIPTION
**Pull request by mythi**

### CODE REVIEW

**Review by mkulke — APPROVED** [review]

**Review by fitzthum — COMMENTED** [review]
Can you add commit message. Otherwise seems good.

**Comment by pawelpros** [comment]
PR tested on Azure environment - works fine

**Comment by mythi** [comment]
commit message added. I also made one addition to `attestation_token_config` (`Jwk` type was missing)

**Review by fitzthum — APPROVED** [review]
LGTM

**Pull request merged**
