### PR TITLE
docker: refactor docker folder structure

### PR DESCRIPTION
**Pull request by pawelpros**
- Refactored AS docker placement
- Refactored RVPS docker placement
- Refactored KBS docker placement

This change improves Dockerfile readability as current approach (format: Dockerfile.[name]) is not compatible with code inspection in IDEs which can lead to errors.

### CODE REVIEW

**Comment by pawelpros** [comment]
This PR will be ready after merge: https://github.com/confidential-containers/trustee/pull/410

**Comment by Xynnn007** [comment]
btw #410 has been merged

**Comment by fitzthum** [comment]
@pawelpros I think we're ready for this after a rebase

**Review by fitzthum — APPROVED** [review]
LGTM

**Pull request merged**
