### PR TITLE
Push AS, RVPS, KBS and KBS Client for arm64

### PR DESCRIPTION
**Pull request by seungukshin**
Pushing AS, RVPS, KBS and KBS Client for arm64 to the project's GHCR using cross-compilation. This is an interim step. The native compilation will be introduced when arm runner is set up for CI.

Related: https://github.com/confidential-containers/trustee/issues/631

### CODE REVIEW

**Review by fitzthum — APPROVED** [review]
LGTM

**Review by huoqifeng — APPROVED** [review]
LGTM
Thank you! @seungukshin

**Comment by huoqifeng** [comment]
I noticed several failures in GHA 
https://github.com/confidential-containers/trustee/actions/runs/12459314627/job/34775998424
https://github.com/confidential-containers/trustee/actions/runs/12459314628/job/34775998845

**Comment by seungukshin** [comment]
Thanks @huoqifeng , I'll check them out

**Pull request merged**
